### ISSUE TITLE
I get instant response back dumped to screen from api

### ISSUE THREAD

**Issue by subdesign** [EvilFreelancer/laravel-manticoresearch#1]
In the below example when I try to loop the result I get back the result object _only_ as a response before I can use it for the loop.
Any idea why? I don't `dd()` or `dump()` the response anywhere:
```php
// I use Lumen, the test movies are already there and indexed
$manticoreSearch = app('manticoresearch');
$search = $manticoreSearch->index('movies');
$bool = new \Manticoresearch\Query\BoolQuery();
$bool->must(new \Manticoresearch\Query\Match(['query' => 'team of explorers', 'operator' => 'and'], 'title,plot'));

$results = $search->search($bool)->get(); // at this line the object is dumped to screen

foreach($results as $doc) {
  echo 'Document:'.$doc->getId()."\n";
  foreach($doc->getData() as $field=>$value)
  {   
      echo $field.": ".$value."\n";
  }
}
```
And the result shown in my browser:
```php
^ Manticoresearch\Response {#98 ▼
  #time: 0.0031960010528564
  #string: "{"took":0,"timed_out":false,"hits":{"total":1,"hits":[{"_id":"2","_score":3565,"_source":{"year":2014,"rating":8.500000,"title":"Interstellar","plot":"A team of ▶"
  #transportInfo: array:3 [▶]
  #status: 200
  #response: array:3 [▶]
}
```
screenshot:
<img width="679" alt="Screenshot 2020-09-16 at 10 32 51" src="https://user-images.githubusercontent.com/691695/93312962-2278f280-f808-11ea-8940-982bed1b84a3.png">

If I try to `dd()` the result nothing happens, above response object shown in browser again:
```php
...
$results = $search->search($bool)->get();

dd($results);

foreach($results as $doc) {
   echo 'Document:'.$doc->getId()."\n";
   foreach($doc->getData() as $field=>$value)
   {   
        echo $field.": ".$value."\n";
   }
}
```
How to process the response I want furthermore, and don't get the response dumped as object ?
Thanks

EDIT: it's in a simple `GET` request method for testing the search

EDIT 2: if I use the package way (and not directly the _manticoresearch-php_ classes), like
`$results = $movies->search('team of explorers')->get();`
the thing is the same

**Comment by EvilFreelancer** [comment]
Hello and thanks for report!

Very interesting issue, I use this library in few of my Laravel project and everything works fine.

> EDIT 2: if I use the package way (and not directly the manticoresearch-php classes), like
> $results = $movies->search('team of explorers')->get();
> the thing is the same

Maybe you have somewhere in some middlewares the dd() method usage? Try:
```bash
grep -n '[\ |^]dd(' ./* -R
```
in root of sources of your project.

**Comment by subdesign** [comment]
Thanks, really I left a `dd` in `Client.php` of Manticoresearch, the strange is that when I searched through the project in Sublime starting from root folder, no `dd` found! Sorry..
Anyway great package!

**Comment by EvilFreelancer** [comment]
Glad to help :)
