### ISSUE TITLE
mysql connection error?

### ISSUE THREAD

**Issue by subdesign** [EvilFreelancer/laravel-manticoresearch#2]
Am I right that I can't connect to Mysql with manticore-php package? As in the docs, the transport layer can be Http, Https only. If not, any hint how to make it work?

`searchd` runs on following ports, and I created an index without error:
```bash
tcp4       0      0  *.9306                 *.*                    LISTEN      131072 131072   9254      0 0x0180 0x00000206
tcp4       0      0  *.9312                 *.*                    LISTEN      131072 131072   9254      0 0x0180 0x00000206
```
`searchd` config:
```bash
searchd
{
    listen                  = 9312
    listen                  = 9306:mysql
    pid_file                = /usr/local/var/run/manticore/searchd.pid
    max_matches             = 1000
    binlog_path             = /var/data
}
```
what should I set for `MANTICORESEARCH_PORT` then in the config file? I tried both 9306 & 9312.

I get the following connection error btw:
```php
^ Manticoresearch\Exceptions\NoMoreNodesException {#97 ▼
  #request: null
  #message: "No more retries left"
  #code: 0
  #file: "/Users/x/web/y/conference-api/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Connection/ConnectionPool.php"
  #line: 62
  trace: {▼
    /Users/x/web/y/conference-api/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Connection/ConnectionPool.php:62 {▶}
    /Users/x/web/y/conference-api/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Client.php:340 {▼
      Manticoresearch\Client->request(Request $request, array $params = []): Response …
      › try {
      ›     $connection = $this->connectionPool->getConnection();
      ›     $this->lastResponse = $connection->getTransportHandler($this->logger)->execute($request, $params);
    }
    /Users/x/web/y/conference-api/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Client.php:359 {▼
      Manticoresearch\Client->request(Request $request, array $params = []): Response …
      › 
      ›     return $this->request($request, $params);
      › }
      arguments: {▶}
    }
    /Users/x/web/y/conference-api/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Client.php:169 {▼
      Manticoresearch\Client->search(array $params = [], $obj = false) …
      › $endpoint = new Endpoints\Search($params);
      › $response = $this->request($endpoint);
      › if ($obj === true) {
      arguments: {▶}
    }
    /Users/x/web/y/conference-api/vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/Search.php:290 {▼
      Manticoresearch\Search->get() …
      › $this->body = $this->compile();
      › $resp = $this->client->search(['body' => $this->body], true);
      › return new ResultSet($resp);
      arguments: {▶}
    }
    /Users/x/web/y/conference-api/app/Http/Controllers/SearchApiController.php:122 {▼
      App\Http\Controllers\SearchApiController->test3() …
      › 
      › $results = $conferences->search('searchterm')->get();
      › 
    }
```

**Comment by sanikolaev** [comment]
Hi. What's your Manticore version?

**Comment by EvilFreelancer** [comment]
@subdesign hello!

`manticore-php` library work with ManticoreSearch server via http(s) protocol, in default configuration of ManticoreSearch a port with http server is `9308`:

https://github.com/manticoresoftware/docker/blob/master/manticore.conf#L83

Same port used in default configuration of `laravel-manticoresearch` project:

https://github.com/EvilFreelancer/laravel-manticoresearch/blob/master/config/manticoresearch.php#L16

So i guess you need just add line like:
```
listen = 9308:http
```
to settings of searchd, then restart service and check connection via library again.

**Comment by subdesign** [comment]
> So i guess you need just add line like:
> 
> ```
> listen = 9308:http
> ```

thanks, this setting works!

**Comment by sanikolaev** [comment]
I asked about your Manticore version, because starting from 3.5.0 you don't need to add `:http`, i.e. just `listen                  = 9312` should work fine for everything (including http) except mysql.

**Comment by subdesign** [comment]
> I asked about your Manticore version, because starting from 3.5.0 you don't need to add `:http`, i.e. just `listen = 9312` should work fine for everything (including http) except mysql.

Thanks. I run 3.4.0 binary from downloaded tar. When I first installed manticore with **brew**, I had problem with the connector dylib, that was for mysql 8.0, and I have 5.7. 
Second, we use 3.4.0 on test servers and the projects work well with that.
