### ISSUE TITLE
Question about Facade

### ISSUE THREAD

**Issue by eloscuro** [EvilFreelancer/laravel-manticoresearch#3]
Hello, 
I cannot understand, how can the following code work (from the README.md file):

```\ManticoreSearch::connection('connectionName')->sql($params);```

... since there is no **ManticoreSearch** class in the package? I just get _"Class "ManticoreSearch"_ not found" error.

And facade class is named **\ManticoreSearch\Laravel\Facade**.

So if I write

```\ManticoreSearch\Laravel\Facade::connection('connectionName')->sql($params);```

.. it works, but it's not very neat syntax.

**Comment by EvilFreelancer** [comment]
Hello! Thanks for your question. Which version of Laravel framework do you use? Or maybe you use Lumen?

**Comment by EvilFreelancer** [comment]
The reason why I need these details is - on Lumen there is no auto detect of Facades (described in [composer.json](https://github.com/EvilFreelancer/laravel-manticoresearch/blob/master/composer.json#L59)), and old Laravel releases is also don't support this feature.

If you have old Laravel or Lumen, then you need to enable this Facade in settings of your application.

**Comment by eloscuro** [comment]
Yes, I'm using Lumen v8.2.4

**Comment by EvilFreelancer** [comment]
Okay, then check this small instruction https://stackoverflow.com/questions/30399766/where-to-register-facades-service-providers-in-lumen

You just need to enable facade with short name in settings.

**Comment by EvilFreelancer** [comment]
These changes should be added to `bootstrap/app.php`

```php
// Enable shortname of facade
$app->withFacades(true, [
    'ManticoreSearch\Laravel\Facade' => 'ManticoreSearch',
]);

// Register Config Files
$app->configure('manticoresearch');

// Register Service Providers
$app->register(ManticoreSearch\Laravel\ServiceProvider::class);
```

**Comment by eloscuro** [comment]
Yes, thank you very much, that helped.
